#define TEXT8	"[Aborted]"
#define	TEXT19	"[Key not bound]"
#define	TEXT32	"Discard changes"
#define	TEXT34	"File: "
#define	TEXT99	"[OUT OF MEMORY]"
#define	TEXT104	"Modified buffers exist. Leave anyway"
#define	TEXT109	"[Key illegal in VIEW mode]"
#define TEXT131 "Read file"
#define	TEXT138	"[New file]"
#define	TEXT139	"[Reading file]"
#define	TEXT140	"Read "
#define	TEXT141	"I/O ERROR, "
#define	TEXT142	"OUT OF MEMORY, "
#define	TEXT143	" line"
#define	TEXT145	"No file name"
#define	TEXT146	"Truncated file..write it out"
#define	TEXT147	"Narrowed Buffer..write it out"
#define	TEXT148	"[Writing...]"
#define	TEXT149	"[Wrote "
#define	TEXT150	", saved as "
#define	TEXT155	"Cannot open file for writing"
#define	TEXT156	"Error closing file"
#define	TEXT157	"Write I/O error"
#define	TEXT158	"File read error"
#define	TEXT162	" [y/n]? "
#define	TEXT170	"bug: linsert"
#define	TEXT182	"Environment variable TERM not defined!"
#define	TEXT183	"Unknown terminal type %s!"
#define	TEXT184	"termcap entry incomplete (lines)"
#define	TEXT185	"Termcap entry incomplete (columns)"
#define	TEXT186	"Incomplete termcap entry\n"
#define	TEXT187	"Terminal description too big!\n"
