/* ALL global fuction declarations */

BUFFER *bfind();
char *bytecopy();
char *fixnull();
char *int_asc();
char *makename();
int absv();
int ernd();
int fexist();
int getkey();
int tgetc();
LINE *lalloc();
int backchar();
int backdel();
int backline();
int backpage();
int bclear();
int cex();
int ctrlg();
int ectoc();
int edinit();
int editloop();
int execute();
int ffclose();
int ffgetline();
int ffputline();
int ffropen();
int ffwopen();
int fileread();
int filesave();
int forwchar();
int forwdel();
int forwline();
int forwpage();
int getccol();
int getcline();
int getcmd();
int getgoal();
int gotobob();
int gotobol();
int gotoeob();
int gotoeol();
int killtext();
int lchange();
int ldelete();
int ldelnewline();
int lfree();
int linsert(int, char);
int lnewline();
int meexit();
int meta();
int mlerase();
int mlout();
int mlyesno();
int modeline();
int movecursor();
int newline();
int quit();
int rdonly();
int readin();
int reframe();
int refresh();
int tab();
int ttclose();
int ttflush();
int ttgetc();
int ttopen();
int ttputc();
int typahead();
int updall();
int update();
int updateline();
int upddex();
int updext();
int updgar();
int updone();
int updpos();
int updupd();
int upmode();
int upscreen();
int vteeol();
int vtinit();
int vtmove();
int vtputc();
int vttidy();
int writeout();
KEYTAB *getbind();

int islower();

int mlwrite();

/* some library redefinitions */

char *strcat();
char *strcpy();
char *malloc();

char *gtfilename ();
char *complete ();

